ARG ALGO_BASE=registry.chengyistudio.com/cxx/algo-base:latest

ARG BUILD_BASE=registry.chengyistudio.com/cxx/algo-base:GFKD
FROM ${BUILD_BASE} AS builder
RUN rm -rf /src /build

WORKDIR /src
COPY CMakeLists.txt ./
COPY src/ ./src/
COPY support/ ./support/
COPY tests/ ./tests/
COPY infra/ ./infra/

RUN cmake -S /src -B /build \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_TESTING=ON \
    && cmake --build /build --parallel \
        --target rd-sink infra-test rd-algorithm-test \
    && ctest --test-dir /build --output-on-failure

FROM ${ALGO_BASE}

WORKDIR /app
COPY --from=builder /build/rd-sink /app/rd-sink

ENTRYPOINT ["/app/rd-sink"]

LABEL io.uestcradar.contract="worker/v2" \
      io.uestcradar.roles="sink" \
      io.uestcradar.input="3:2" \
      io.uestcradar.output="3:2"
