// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package previewfb

import (
	"strconv"

	flatbuffers "github.com/google/flatbuffers/go"
)

type Leg byte

const (
	LegUnknown Leg = 0
	LegInput   Leg = 1
	LegOutput  Leg = 2
)

var EnumNamesLeg = map[Leg]string{
	LegUnknown: "Unknown",
	LegInput:   "Input",
	LegOutput:  "Output",
}

var EnumValuesLeg = map[string]Leg{
	"Unknown": LegUnknown,
	"Input":   LegInput,
	"Output":  LegOutput,
}

func (v Leg) String() string {
	if s, ok := EnumNamesLeg[v]; ok {
		return s
	}
	return "Leg(" + strconv.FormatInt(int64(v), 10) + ")"
}

type ValueEncoding byte

const (
	ValueEncodingUnknown        ValueEncoding = 0
	ValueEncodingComplexInt8    ValueEncoding = 1
	ValueEncodingComplexFloat16 ValueEncoding = 2
	ValueEncodingFloat16        ValueEncoding = 3
)

var EnumNamesValueEncoding = map[ValueEncoding]string{
	ValueEncodingUnknown:        "Unknown",
	ValueEncodingComplexInt8:    "ComplexInt8",
	ValueEncodingComplexFloat16: "ComplexFloat16",
	ValueEncodingFloat16:        "Float16",
}

var EnumValuesValueEncoding = map[string]ValueEncoding{
	"Unknown":        ValueEncodingUnknown,
	"ComplexInt8":    ValueEncodingComplexInt8,
	"ComplexFloat16": ValueEncodingComplexFloat16,
	"Float16":        ValueEncodingFloat16,
}

func (v ValueEncoding) String() string {
	if s, ok := EnumNamesValueEncoding[v]; ok {
		return s
	}
	return "ValueEncoding(" + strconv.FormatInt(int64(v), 10) + ")"
}

type PreviewBody byte

const (
	PreviewBodyNONE            PreviewBody = 0
	PreviewBodyWaveformPreview PreviewBody = 1
	PreviewBodyHeatmapPreview  PreviewBody = 2
)

var EnumNamesPreviewBody = map[PreviewBody]string{
	PreviewBodyNONE:            "NONE",
	PreviewBodyWaveformPreview: "WaveformPreview",
	PreviewBodyHeatmapPreview:  "HeatmapPreview",
}

var EnumValuesPreviewBody = map[string]PreviewBody{
	"NONE":            PreviewBodyNONE,
	"WaveformPreview": PreviewBodyWaveformPreview,
	"HeatmapPreview":  PreviewBodyHeatmapPreview,
}

func (v PreviewBody) String() string {
	if s, ok := EnumNamesPreviewBody[v]; ok {
		return s
	}
	return "PreviewBody(" + strconv.FormatInt(int64(v), 10) + ")"
}

type MessagePayload byte

const (
	MessagePayloadNONE               MessagePayload = 0
	MessagePayloadSidecarHello       MessagePayload = 1
	MessagePayloadSubscriptionUpdate MessagePayload = 2
	MessagePayloadPreviewFrame       MessagePayload = 3
	MessagePayloadStreamStatus       MessagePayload = 4
)

var EnumNamesMessagePayload = map[MessagePayload]string{
	MessagePayloadNONE:               "NONE",
	MessagePayloadSidecarHello:       "SidecarHello",
	MessagePayloadSubscriptionUpdate: "SubscriptionUpdate",
	MessagePayloadPreviewFrame:       "PreviewFrame",
	MessagePayloadStreamStatus:       "StreamStatus",
}

var EnumValuesMessagePayload = map[string]MessagePayload{
	"NONE":               MessagePayloadNONE,
	"SidecarHello":       MessagePayloadSidecarHello,
	"SubscriptionUpdate": MessagePayloadSubscriptionUpdate,
	"PreviewFrame":       MessagePayloadPreviewFrame,
	"StreamStatus":       MessagePayloadStreamStatus,
}

func (v MessagePayload) String() string {
	if s, ok := EnumNamesMessagePayload[v]; ok {
		return s
	}
	return "MessagePayload(" + strconv.FormatInt(int64(v), 10) + ")"
}

type StreamDescriptor struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamDescriptor(buf []byte, offset flatbuffers.UOffsetT) *StreamDescriptor {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamDescriptor{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamDescriptor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamDescriptor) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamDescriptor) Leg() Leg {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Leg(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StreamDescriptor) MutateLeg(n Leg) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *StreamDescriptor) FrameTypeId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamDescriptor) MutateFrameTypeId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *StreamDescriptor) FrameTypeVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamDescriptor) MutateFrameTypeVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func StreamDescriptorStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func StreamDescriptorAddLeg(builder *flatbuffers.Builder, leg Leg) {
	builder.PrependByteSlot(0, byte(leg), 0)
}
func StreamDescriptorAddFrameTypeId(builder *flatbuffers.Builder, frameTypeId uint64) {
	builder.PrependUint64Slot(1, frameTypeId, 0)
}
func StreamDescriptorAddFrameTypeVersion(builder *flatbuffers.Builder, frameTypeVersion uint32) {
	builder.PrependUint32Slot(2, frameTypeVersion, 0)
}
func StreamDescriptorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type SidecarHello struct {
	_tab flatbuffers.Table
}

func GetRootAsSidecarHello(buf []byte, offset flatbuffers.UOffsetT) *SidecarHello {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SidecarHello{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SidecarHello) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SidecarHello) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SidecarHello) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SidecarHello) InstanceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SidecarHello) Streams(obj *StreamDescriptor, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SidecarHello) StreamsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SidecarHelloStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SidecarHelloAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeId), 0)
}
func SidecarHelloAddInstanceId(builder *flatbuffers.Builder, instanceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(instanceId), 0)
}
func SidecarHelloAddStreams(builder *flatbuffers.Builder, streams flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(streams), 0)
}
func SidecarHelloStartStreamsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SidecarHelloEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type StreamSelector struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamSelector(buf []byte, offset flatbuffers.UOffsetT) *StreamSelector {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamSelector{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamSelector) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamSelector) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamSelector) SubscriptionId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamSelector) MutateSubscriptionId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *StreamSelector) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamSelector) Leg() Leg {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return Leg(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StreamSelector) MutateLeg(n Leg) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *StreamSelector) FrameTypeId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamSelector) MutateFrameTypeId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *StreamSelector) FrameTypeVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamSelector) MutateFrameTypeVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *StreamSelector) RequestedFps() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 30.0
}

func (rcv *StreamSelector) MutateRequestedFps(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func StreamSelectorStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func StreamSelectorAddSubscriptionId(builder *flatbuffers.Builder, subscriptionId uint64) {
	builder.PrependUint64Slot(0, subscriptionId, 0)
}
func StreamSelectorAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(nodeId), 0)
}
func StreamSelectorAddLeg(builder *flatbuffers.Builder, leg Leg) {
	builder.PrependByteSlot(2, byte(leg), 0)
}
func StreamSelectorAddFrameTypeId(builder *flatbuffers.Builder, frameTypeId uint64) {
	builder.PrependUint64Slot(3, frameTypeId, 0)
}
func StreamSelectorAddFrameTypeVersion(builder *flatbuffers.Builder, frameTypeVersion uint32) {
	builder.PrependUint32Slot(4, frameTypeVersion, 0)
}
func StreamSelectorAddRequestedFps(builder *flatbuffers.Builder, requestedFps float32) {
	builder.PrependFloat32Slot(5, requestedFps, 30.0)
}
func StreamSelectorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type SubscriptionUpdate struct {
	_tab flatbuffers.Table
}

func GetRootAsSubscriptionUpdate(buf []byte, offset flatbuffers.UOffsetT) *SubscriptionUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SubscriptionUpdate{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SubscriptionUpdate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SubscriptionUpdate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SubscriptionUpdate) Version() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SubscriptionUpdate) MutateVersion(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *SubscriptionUpdate) Selectors(obj *StreamSelector, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SubscriptionUpdate) SelectorsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SubscriptionUpdateStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SubscriptionUpdateAddVersion(builder *flatbuffers.Builder, version uint64) {
	builder.PrependUint64Slot(0, version, 0)
}
func SubscriptionUpdateAddSelectors(builder *flatbuffers.Builder, selectors flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(selectors), 0)
}
func SubscriptionUpdateStartSelectorsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SubscriptionUpdateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type WaveformChannel struct {
	_tab flatbuffers.Table
}

func GetRootAsWaveformChannel(buf []byte, offset flatbuffers.UOffsetT) *WaveformChannel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WaveformChannel{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *WaveformChannel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WaveformChannel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WaveformChannel) ChannelIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *WaveformChannel) MutateChannelIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *WaveformChannel) BucketCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *WaveformChannel) MutateBucketCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *WaveformChannel) Scale() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 1.0
}

func (rcv *WaveformChannel) MutateScale(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *WaveformChannel) MinOffsets(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *WaveformChannel) MinOffsetsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *WaveformChannel) MinOffsetsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WaveformChannel) MutateMinOffsets(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *WaveformChannel) MaxOffsets(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *WaveformChannel) MaxOffsetsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *WaveformChannel) MaxOffsetsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WaveformChannel) MutateMaxOffsets(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *WaveformChannel) Values(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *WaveformChannel) ValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *WaveformChannel) ValuesBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WaveformChannel) MutateValues(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func WaveformChannelStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func WaveformChannelAddChannelIndex(builder *flatbuffers.Builder, channelIndex uint32) {
	builder.PrependUint32Slot(0, channelIndex, 0)
}
func WaveformChannelAddBucketCount(builder *flatbuffers.Builder, bucketCount uint32) {
	builder.PrependUint32Slot(1, bucketCount, 0)
}
func WaveformChannelAddScale(builder *flatbuffers.Builder, scale float32) {
	builder.PrependFloat32Slot(2, scale, 1.0)
}
func WaveformChannelAddMinOffsets(builder *flatbuffers.Builder, minOffsets flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(minOffsets), 0)
}
func WaveformChannelStartMinOffsetsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func WaveformChannelAddMaxOffsets(builder *flatbuffers.Builder, maxOffsets flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(maxOffsets), 0)
}
func WaveformChannelStartMaxOffsetsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func WaveformChannelAddValues(builder *flatbuffers.Builder, values flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(values), 0)
}
func WaveformChannelStartValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func WaveformChannelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type WaveformPreview struct {
	_tab flatbuffers.Table
}

func GetRootAsWaveformPreview(buf []byte, offset flatbuffers.UOffsetT) *WaveformPreview {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WaveformPreview{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *WaveformPreview) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WaveformPreview) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WaveformPreview) Channels(obj *WaveformChannel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *WaveformPreview) ChannelsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func WaveformPreviewStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WaveformPreviewAddChannels(builder *flatbuffers.Builder, channels flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(channels), 0)
}
func WaveformPreviewStartChannelsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func WaveformPreviewEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type HeatmapPreview struct {
	_tab flatbuffers.Table
}

func GetRootAsHeatmapPreview(buf []byte, offset flatbuffers.UOffsetT) *HeatmapPreview {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HeatmapPreview{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *HeatmapPreview) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HeatmapPreview) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HeatmapPreview) ChannelIndex() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HeatmapPreview) MutateChannelIndex(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *HeatmapPreview) Rows() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HeatmapPreview) MutateRows(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *HeatmapPreview) Columns() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HeatmapPreview) MutateColumns(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *HeatmapPreview) MaxOffsets(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *HeatmapPreview) MaxOffsetsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *HeatmapPreview) MaxOffsetsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *HeatmapPreview) MutateMaxOffsets(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *HeatmapPreview) Values(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *HeatmapPreview) ValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *HeatmapPreview) ValuesBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *HeatmapPreview) MutateValues(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func HeatmapPreviewStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func HeatmapPreviewAddChannelIndex(builder *flatbuffers.Builder, channelIndex uint32) {
	builder.PrependUint32Slot(0, channelIndex, 0)
}
func HeatmapPreviewAddRows(builder *flatbuffers.Builder, rows uint32) {
	builder.PrependUint32Slot(1, rows, 0)
}
func HeatmapPreviewAddColumns(builder *flatbuffers.Builder, columns uint32) {
	builder.PrependUint32Slot(2, columns, 0)
}
func HeatmapPreviewAddMaxOffsets(builder *flatbuffers.Builder, maxOffsets flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(maxOffsets), 0)
}
func HeatmapPreviewStartMaxOffsetsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func HeatmapPreviewAddValues(builder *flatbuffers.Builder, values flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(values), 0)
}
func HeatmapPreviewStartValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func HeatmapPreviewEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type PreviewFrame struct {
	_tab flatbuffers.Table
}

func GetRootAsPreviewFrame(buf []byte, offset flatbuffers.UOffsetT) *PreviewFrame {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PreviewFrame{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PreviewFrame) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PreviewFrame) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PreviewFrame) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PreviewFrame) InstanceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PreviewFrame) Leg() Leg {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return Leg(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PreviewFrame) MutateLeg(n Leg) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *PreviewFrame) FrameTypeId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PreviewFrame) MutateFrameTypeId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *PreviewFrame) FrameTypeVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PreviewFrame) MutateFrameTypeVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *PreviewFrame) FrameId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PreviewFrame) MutateFrameId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *PreviewFrame) TimestampNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PreviewFrame) MutateTimestampNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *PreviewFrame) OriginalRows() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PreviewFrame) MutateOriginalRows(n uint32) bool {
	return rcv._tab.MutateUint32Slot(18, n)
}

func (rcv *PreviewFrame) OriginalColumns() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PreviewFrame) MutateOriginalColumns(n uint32) bool {
	return rcv._tab.MutateUint32Slot(20, n)
}

func (rcv *PreviewFrame) PoolRows() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PreviewFrame) MutatePoolRows(n uint32) bool {
	return rcv._tab.MutateUint32Slot(22, n)
}

func (rcv *PreviewFrame) PoolColumns() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PreviewFrame) MutatePoolColumns(n uint32) bool {
	return rcv._tab.MutateUint32Slot(24, n)
}

func (rcv *PreviewFrame) Encoding() ValueEncoding {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return ValueEncoding(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PreviewFrame) MutateEncoding(n ValueEncoding) bool {
	return rcv._tab.MutateByteSlot(26, byte(n))
}

func (rcv *PreviewFrame) Metadata(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PreviewFrame) MetadataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PreviewFrame) MetadataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PreviewFrame) MutateMetadata(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *PreviewFrame) BodyType() PreviewBody {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return PreviewBody(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PreviewFrame) MutateBodyType(n PreviewBody) bool {
	return rcv._tab.MutateByteSlot(30, byte(n))
}

func (rcv *PreviewFrame) Body(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func PreviewFrameStart(builder *flatbuffers.Builder) {
	builder.StartObject(15)
}
func PreviewFrameAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeId), 0)
}
func PreviewFrameAddInstanceId(builder *flatbuffers.Builder, instanceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(instanceId), 0)
}
func PreviewFrameAddLeg(builder *flatbuffers.Builder, leg Leg) {
	builder.PrependByteSlot(2, byte(leg), 0)
}
func PreviewFrameAddFrameTypeId(builder *flatbuffers.Builder, frameTypeId uint64) {
	builder.PrependUint64Slot(3, frameTypeId, 0)
}
func PreviewFrameAddFrameTypeVersion(builder *flatbuffers.Builder, frameTypeVersion uint32) {
	builder.PrependUint32Slot(4, frameTypeVersion, 0)
}
func PreviewFrameAddFrameId(builder *flatbuffers.Builder, frameId uint64) {
	builder.PrependUint64Slot(5, frameId, 0)
}
func PreviewFrameAddTimestampNs(builder *flatbuffers.Builder, timestampNs uint64) {
	builder.PrependUint64Slot(6, timestampNs, 0)
}
func PreviewFrameAddOriginalRows(builder *flatbuffers.Builder, originalRows uint32) {
	builder.PrependUint32Slot(7, originalRows, 0)
}
func PreviewFrameAddOriginalColumns(builder *flatbuffers.Builder, originalColumns uint32) {
	builder.PrependUint32Slot(8, originalColumns, 0)
}
func PreviewFrameAddPoolRows(builder *flatbuffers.Builder, poolRows uint32) {
	builder.PrependUint32Slot(9, poolRows, 0)
}
func PreviewFrameAddPoolColumns(builder *flatbuffers.Builder, poolColumns uint32) {
	builder.PrependUint32Slot(10, poolColumns, 0)
}
func PreviewFrameAddEncoding(builder *flatbuffers.Builder, encoding ValueEncoding) {
	builder.PrependByteSlot(11, byte(encoding), 0)
}
func PreviewFrameAddMetadata(builder *flatbuffers.Builder, metadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(metadata), 0)
}
func PreviewFrameStartMetadataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PreviewFrameAddBodyType(builder *flatbuffers.Builder, bodyType PreviewBody) {
	builder.PrependByteSlot(13, byte(bodyType), 0)
}
func PreviewFrameAddBody(builder *flatbuffers.Builder, body flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(body), 0)
}
func PreviewFrameEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type StreamStatus struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamStatus(buf []byte, offset flatbuffers.UOffsetT) *StreamStatus {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamStatus{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamStatus) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamStatus) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamStatus) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamStatus) Leg() Leg {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return Leg(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StreamStatus) MutateLeg(n Leg) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *StreamStatus) FrameTypeId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamStatus) MutateFrameTypeId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *StreamStatus) FrameTypeVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamStatus) MutateFrameTypeVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *StreamStatus) ActualFps() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StreamStatus) MutateActualFps(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *StreamStatus) SnapshotDrops() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamStatus) MutateSnapshotDrops(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *StreamStatus) EncodeDrops() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamStatus) MutateEncodeDrops(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *StreamStatus) NetworkDrops() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamStatus) MutateNetworkDrops(n uint64) bool {
	return rcv._tab.MutateUint64Slot(18, n)
}

func StreamStatusStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func StreamStatusAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeId), 0)
}
func StreamStatusAddLeg(builder *flatbuffers.Builder, leg Leg) {
	builder.PrependByteSlot(1, byte(leg), 0)
}
func StreamStatusAddFrameTypeId(builder *flatbuffers.Builder, frameTypeId uint64) {
	builder.PrependUint64Slot(2, frameTypeId, 0)
}
func StreamStatusAddFrameTypeVersion(builder *flatbuffers.Builder, frameTypeVersion uint32) {
	builder.PrependUint32Slot(3, frameTypeVersion, 0)
}
func StreamStatusAddActualFps(builder *flatbuffers.Builder, actualFps float32) {
	builder.PrependFloat32Slot(4, actualFps, 0.0)
}
func StreamStatusAddSnapshotDrops(builder *flatbuffers.Builder, snapshotDrops uint64) {
	builder.PrependUint64Slot(5, snapshotDrops, 0)
}
func StreamStatusAddEncodeDrops(builder *flatbuffers.Builder, encodeDrops uint64) {
	builder.PrependUint64Slot(6, encodeDrops, 0)
}
func StreamStatusAddNetworkDrops(builder *flatbuffers.Builder, networkDrops uint64) {
	builder.PrependUint64Slot(7, networkDrops, 0)
}
func StreamStatusEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

type PreviewMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsPreviewMessage(buf []byte, offset flatbuffers.UOffsetT) *PreviewMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PreviewMessage{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PreviewMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PreviewMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PreviewMessage) ProtocolVersion() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *PreviewMessage) MutateProtocolVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *PreviewMessage) PayloadType() MessagePayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return MessagePayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PreviewMessage) MutatePayloadType(n MessagePayload) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *PreviewMessage) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func PreviewMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PreviewMessageAddProtocolVersion(builder *flatbuffers.Builder, protocolVersion uint16) {
	builder.PrependUint16Slot(0, protocolVersion, 1)
}
func PreviewMessageAddPayloadType(builder *flatbuffers.Builder, payloadType MessagePayload) {
	builder.PrependByteSlot(1, byte(payloadType), 0)
}
func PreviewMessageAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(payload), 0)
}
func PreviewMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
