// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: telemetry.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkDirection int32

const (
	LinkDirection_LINK_DIRECTION_UNSPECIFIED LinkDirection = 0
	LinkDirection_LINK_DIRECTION_INGRESS     LinkDirection = 1
	LinkDirection_LINK_DIRECTION_EGRESS      LinkDirection = 2
)

// Enum value maps for LinkDirection.
var (
	LinkDirection_name = map[int32]string{
		0: "LINK_DIRECTION_UNSPECIFIED",
		1: "LINK_DIRECTION_INGRESS",
		2: "LINK_DIRECTION_EGRESS",
	}
	LinkDirection_value = map[string]int32{
		"LINK_DIRECTION_UNSPECIFIED": 0,
		"LINK_DIRECTION_INGRESS":     1,
		"LINK_DIRECTION_EGRESS":      2,
	}
)

func (x LinkDirection) Enum() *LinkDirection {
	p := new(LinkDirection)
	*p = x
	return p
}

func (x LinkDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[0].Descriptor()
}

func (LinkDirection) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[0]
}

func (x LinkDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkDirection.Descriptor instead.
func (LinkDirection) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

type LinkConnectionState int32

const (
	LinkConnectionState_LINK_CONNECTION_STATE_UNSPECIFIED  LinkConnectionState = 0
	LinkConnectionState_LINK_CONNECTION_STATE_DISABLED     LinkConnectionState = 1
	LinkConnectionState_LINK_CONNECTION_STATE_DISCONNECTED LinkConnectionState = 2
	LinkConnectionState_LINK_CONNECTION_STATE_CONNECTED    LinkConnectionState = 3
)

// Enum value maps for LinkConnectionState.
var (
	LinkConnectionState_name = map[int32]string{
		0: "LINK_CONNECTION_STATE_UNSPECIFIED",
		1: "LINK_CONNECTION_STATE_DISABLED",
		2: "LINK_CONNECTION_STATE_DISCONNECTED",
		3: "LINK_CONNECTION_STATE_CONNECTED",
	}
	LinkConnectionState_value = map[string]int32{
		"LINK_CONNECTION_STATE_UNSPECIFIED":  0,
		"LINK_CONNECTION_STATE_DISABLED":     1,
		"LINK_CONNECTION_STATE_DISCONNECTED": 2,
		"LINK_CONNECTION_STATE_CONNECTED":    3,
	}
)

func (x LinkConnectionState) Enum() *LinkConnectionState {
	p := new(LinkConnectionState)
	*p = x
	return p
}

func (x LinkConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[1].Descriptor()
}

func (LinkConnectionState) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[1]
}

func (x LinkConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkConnectionState.Descriptor instead.
func (LinkConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

type TransportKind int32

const (
	TransportKind_TRANSPORT_KIND_UNSPECIFIED TransportKind = 0
	TransportKind_TRANSPORT_KIND_TCP         TransportKind = 1
	TransportKind_TRANSPORT_KIND_RDMA        TransportKind = 2
)

// Enum value maps for TransportKind.
var (
	TransportKind_name = map[int32]string{
		0: "TRANSPORT_KIND_UNSPECIFIED",
		1: "TRANSPORT_KIND_TCP",
		2: "TRANSPORT_KIND_RDMA",
	}
	TransportKind_value = map[string]int32{
		"TRANSPORT_KIND_UNSPECIFIED": 0,
		"TRANSPORT_KIND_TCP":         1,
		"TRANSPORT_KIND_RDMA":        2,
	}
)

func (x TransportKind) Enum() *TransportKind {
	p := new(TransportKind)
	*p = x
	return p
}

func (x TransportKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportKind) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[2].Descriptor()
}

func (TransportKind) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[2]
}

func (x TransportKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportKind.Descriptor instead.
func (TransportKind) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

type RingBufferMetric struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LinkId         string                 `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Sequence       uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObservedUnixNs uint64                 `protobuf:"varint,4,opt,name=observed_unix_ns,json=observedUnixNs,proto3" json:"observed_unix_ns,omitempty"`
	CapacityBytes  uint64                 `protobuf:"varint,5,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	UsedBytes      uint64                 `protobuf:"varint,6,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	WritePosition  uint64                 `protobuf:"varint,7,opt,name=write_position,json=writePosition,proto3" json:"write_position,omitempty"`
	ReadPosition   uint64                 `protobuf:"varint,8,opt,name=read_position,json=readPosition,proto3" json:"read_position,omitempty"`
	Shutdown       bool                   `protobuf:"varint,9,opt,name=shutdown,proto3" json:"shutdown,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RingBufferMetric) Reset() {
	*x = RingBufferMetric{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RingBufferMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingBufferMetric) ProtoMessage() {}

func (x *RingBufferMetric) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingBufferMetric.ProtoReflect.Descriptor instead.
func (*RingBufferMetric) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *RingBufferMetric) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RingBufferMetric) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *RingBufferMetric) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RingBufferMetric) GetObservedUnixNs() uint64 {
	if x != nil {
		return x.ObservedUnixNs
	}
	return 0
}

func (x *RingBufferMetric) GetCapacityBytes() uint64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *RingBufferMetric) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *RingBufferMetric) GetWritePosition() uint64 {
	if x != nil {
		return x.WritePosition
	}
	return 0
}

func (x *RingBufferMetric) GetReadPosition() uint64 {
	if x != nil {
		return x.ReadPosition
	}
	return 0
}

func (x *RingBufferMetric) GetShutdown() bool {
	if x != nil {
		return x.Shutdown
	}
	return false
}

type RingBufferSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapacitySlots uint32                 `protobuf:"varint,1,opt,name=capacity_slots,json=capacitySlots,proto3" json:"capacity_slots,omitempty"`
	UsedSlots     uint32                 `protobuf:"varint,2,opt,name=used_slots,json=usedSlots,proto3" json:"used_slots,omitempty"`
	WritePosition uint64                 `protobuf:"varint,3,opt,name=write_position,json=writePosition,proto3" json:"write_position,omitempty"`
	ReadPosition  uint64                 `protobuf:"varint,4,opt,name=read_position,json=readPosition,proto3" json:"read_position,omitempty"`
	Shutdown      bool                   `protobuf:"varint,5,opt,name=shutdown,proto3" json:"shutdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RingBufferSnapshot) Reset() {
	*x = RingBufferSnapshot{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RingBufferSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingBufferSnapshot) ProtoMessage() {}

func (x *RingBufferSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingBufferSnapshot.ProtoReflect.Descriptor instead.
func (*RingBufferSnapshot) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *RingBufferSnapshot) GetCapacitySlots() uint32 {
	if x != nil {
		return x.CapacitySlots
	}
	return 0
}

func (x *RingBufferSnapshot) GetUsedSlots() uint32 {
	if x != nil {
		return x.UsedSlots
	}
	return 0
}

func (x *RingBufferSnapshot) GetWritePosition() uint64 {
	if x != nil {
		return x.WritePosition
	}
	return 0
}

func (x *RingBufferSnapshot) GetReadPosition() uint64 {
	if x != nil {
		return x.ReadPosition
	}
	return 0
}

func (x *RingBufferSnapshot) GetShutdown() bool {
	if x != nil {
		return x.Shutdown
	}
	return false
}

type LinkMetric struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LinkId            string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	PeerNodeId        string                 `protobuf:"bytes,2,opt,name=peer_node_id,json=peerNodeId,proto3" json:"peer_node_id,omitempty"`
	Direction         LinkDirection          `protobuf:"varint,3,opt,name=direction,proto3,enum=cycomm.telemetry.v1.LinkDirection" json:"direction,omitempty"`
	ConnectionState   LinkConnectionState    `protobuf:"varint,4,opt,name=connection_state,json=connectionState,proto3,enum=cycomm.telemetry.v1.LinkConnectionState" json:"connection_state,omitempty"`
	Transport         TransportKind          `protobuf:"varint,5,opt,name=transport,proto3,enum=cycomm.telemetry.v1.TransportKind" json:"transport,omitempty"`
	PayloadBytesTotal uint64                 `protobuf:"varint,6,opt,name=payload_bytes_total,json=payloadBytesTotal,proto3" json:"payload_bytes_total,omitempty"`
	Ring              *RingBufferSnapshot    `protobuf:"bytes,7,opt,name=ring,proto3" json:"ring,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LinkMetric) Reset() {
	*x = LinkMetric{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkMetric) ProtoMessage() {}

func (x *LinkMetric) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkMetric.ProtoReflect.Descriptor instead.
func (*LinkMetric) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *LinkMetric) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *LinkMetric) GetPeerNodeId() string {
	if x != nil {
		return x.PeerNodeId
	}
	return ""
}

func (x *LinkMetric) GetDirection() LinkDirection {
	if x != nil {
		return x.Direction
	}
	return LinkDirection_LINK_DIRECTION_UNSPECIFIED
}

func (x *LinkMetric) GetConnectionState() LinkConnectionState {
	if x != nil {
		return x.ConnectionState
	}
	return LinkConnectionState_LINK_CONNECTION_STATE_UNSPECIFIED
}

func (x *LinkMetric) GetTransport() TransportKind {
	if x != nil {
		return x.Transport
	}
	return TransportKind_TRANSPORT_KIND_UNSPECIFIED
}

func (x *LinkMetric) GetPayloadBytesTotal() uint64 {
	if x != nil {
		return x.PayloadBytesTotal
	}
	return 0
}

func (x *LinkMetric) GetRing() *RingBufferSnapshot {
	if x != nil {
		return x.Ring
	}
	return nil
}

type NodeHeartbeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	InstanceId     string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Sequence       uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ObservedUnixNs uint64                 `protobuf:"varint,4,opt,name=observed_unix_ns,json=observedUnixNs,proto3" json:"observed_unix_ns,omitempty"`
	Links          []*LinkMetric          `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeHeartbeat) Reset() {
	*x = NodeHeartbeat{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeartbeat) ProtoMessage() {}

func (x *NodeHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeartbeat.ProtoReflect.Descriptor instead.
func (*NodeHeartbeat) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *NodeHeartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeHeartbeat) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *NodeHeartbeat) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *NodeHeartbeat) GetObservedUnixNs() uint64 {
	if x != nil {
		return x.ObservedUnixNs
	}
	return 0
}

func (x *NodeHeartbeat) GetLinks() []*LinkMetric {
	if x != nil {
		return x.Links
	}
	return nil
}

type TelemetryPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in telemetry.proto.
	Rings         []*RingBufferMetric `protobuf:"bytes,1,rep,name=rings,proto3" json:"rings,omitempty"`
	Heartbeat     *NodeHeartbeat      `protobuf:"bytes,2,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPacket) Reset() {
	*x = TelemetryPacket{}
	mi := &file_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPacket) ProtoMessage() {}

func (x *TelemetryPacket) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPacket.ProtoReflect.Descriptor instead.
func (*TelemetryPacket) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{4}
}

// Deprecated: Marked as deprecated in telemetry.proto.
func (x *TelemetryPacket) GetRings() []*RingBufferMetric {
	if x != nil {
		return x.Rings
	}
	return nil
}

func (x *TelemetryPacket) GetHeartbeat() *NodeHeartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\x13cycomm.telemetry.v1\"\xb8\x02\n" +
	"\x10RingBufferMetric\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\alink_id\x18\x02 \x01(\tR\x06linkId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12(\n" +
	"\x10observed_unix_ns\x18\x04 \x01(\x04R\x0eobservedUnixNs\x12%\n" +
	"\x0ecapacity_bytes\x18\x05 \x01(\x04R\rcapacityBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x06 \x01(\x04R\tusedBytes\x12%\n" +
	"\x0ewrite_position\x18\a \x01(\x04R\rwritePosition\x12#\n" +
	"\rread_position\x18\b \x01(\x04R\freadPosition\x12\x1a\n" +
	"\bshutdown\x18\t \x01(\bR\bshutdown\"\xc2\x01\n" +
	"\x12RingBufferSnapshot\x12%\n" +
	"\x0ecapacity_slots\x18\x01 \x01(\rR\rcapacitySlots\x12\x1d\n" +
	"\n" +
	"used_slots\x18\x02 \x01(\rR\tusedSlots\x12%\n" +
	"\x0ewrite_position\x18\x03 \x01(\x04R\rwritePosition\x12#\n" +
	"\rread_position\x18\x04 \x01(\x04R\freadPosition\x12\x1a\n" +
	"\bshutdown\x18\x05 \x01(\bR\bshutdown\"\x8d\x03\n" +
	"\n" +
	"LinkMetric\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12 \n" +
	"\fpeer_node_id\x18\x02 \x01(\tR\n" +
	"peerNodeId\x12@\n" +
	"\tdirection\x18\x03 \x01(\x0e2\".cycomm.telemetry.v1.LinkDirectionR\tdirection\x12S\n" +
	"\x10connection_state\x18\x04 \x01(\x0e2(.cycomm.telemetry.v1.LinkConnectionStateR\x0fconnectionState\x12@\n" +
	"\ttransport\x18\x05 \x01(\x0e2\".cycomm.telemetry.v1.TransportKindR\ttransport\x12.\n" +
	"\x13payload_bytes_total\x18\x06 \x01(\x04R\x11payloadBytesTotal\x12;\n" +
	"\x04ring\x18\a \x01(\v2'.cycomm.telemetry.v1.RingBufferSnapshotR\x04ring\"\xc6\x01\n" +
	"\rNodeHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12(\n" +
	"\x10observed_unix_ns\x18\x04 \x01(\x04R\x0eobservedUnixNs\x125\n" +
	"\x05links\x18\x05 \x03(\v2\x1f.cycomm.telemetry.v1.LinkMetricR\x05links\"\x94\x01\n" +
	"\x0fTelemetryPacket\x12?\n" +
	"\x05rings\x18\x01 \x03(\v2%.cycomm.telemetry.v1.RingBufferMetricB\x02\x18\x01R\x05rings\x12@\n" +
	"\theartbeat\x18\x02 \x01(\v2\".cycomm.telemetry.v1.NodeHeartbeatR\theartbeat*f\n" +
	"\rLinkDirection\x12\x1e\n" +
	"\x1aLINK_DIRECTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16LINK_DIRECTION_INGRESS\x10\x01\x12\x19\n" +
	"\x15LINK_DIRECTION_EGRESS\x10\x02*\xad\x01\n" +
	"\x13LinkConnectionState\x12%\n" +
	"!LINK_CONNECTION_STATE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eLINK_CONNECTION_STATE_DISABLED\x10\x01\x12&\n" +
	"\"LINK_CONNECTION_STATE_DISCONNECTED\x10\x02\x12#\n" +
	"\x1fLINK_CONNECTION_STATE_CONNECTED\x10\x03*`\n" +
	"\rTransportKind\x12\x1e\n" +
	"\x1aTRANSPORT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TRANSPORT_KIND_TCP\x10\x01\x12\x17\n" +
	"\x13TRANSPORT_KIND_RDMA\x10\x02B-H\x03Z)uestcradar/telemetry/internal/telemetrypbb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_telemetry_proto_goTypes = []any{
	(LinkDirection)(0),         // 0: cycomm.telemetry.v1.LinkDirection
	(LinkConnectionState)(0),   // 1: cycomm.telemetry.v1.LinkConnectionState
	(TransportKind)(0),         // 2: cycomm.telemetry.v1.TransportKind
	(*RingBufferMetric)(nil),   // 3: cycomm.telemetry.v1.RingBufferMetric
	(*RingBufferSnapshot)(nil), // 4: cycomm.telemetry.v1.RingBufferSnapshot
	(*LinkMetric)(nil),         // 5: cycomm.telemetry.v1.LinkMetric
	(*NodeHeartbeat)(nil),      // 6: cycomm.telemetry.v1.NodeHeartbeat
	(*TelemetryPacket)(nil),    // 7: cycomm.telemetry.v1.TelemetryPacket
}
var file_telemetry_proto_depIdxs = []int32{
	0, // 0: cycomm.telemetry.v1.LinkMetric.direction:type_name -> cycomm.telemetry.v1.LinkDirection
	1, // 1: cycomm.telemetry.v1.LinkMetric.connection_state:type_name -> cycomm.telemetry.v1.LinkConnectionState
	2, // 2: cycomm.telemetry.v1.LinkMetric.transport:type_name -> cycomm.telemetry.v1.TransportKind
	4, // 3: cycomm.telemetry.v1.LinkMetric.ring:type_name -> cycomm.telemetry.v1.RingBufferSnapshot
	5, // 4: cycomm.telemetry.v1.NodeHeartbeat.links:type_name -> cycomm.telemetry.v1.LinkMetric
	3, // 5: cycomm.telemetry.v1.TelemetryPacket.rings:type_name -> cycomm.telemetry.v1.RingBufferMetric
	6, // 6: cycomm.telemetry.v1.TelemetryPacket.heartbeat:type_name -> cycomm.telemetry.v1.NodeHeartbeat
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		EnumInfos:         file_telemetry_proto_enumTypes,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
