function analyze_bin_gui
%ANALYZE_BIN_GUI Select and scan one continuous CYHD BIN capture.
%   Run ANALYZE_BIN_GUI from MATLAB.  Selecting a BIN starts scanning and
%   writes <bin-stem>_record_info.mat beside the selected source file.

    bgColor = [0.95, 0.96, 0.98];
    panelColor = [1.00, 1.00, 1.00];
    textColor = [0.10, 0.12, 0.16];
    secondaryColor = [0.35, 0.38, 0.45];

    fig = uifigure( ...
        'Name', 'CYHD BIN 数据质量检查', ...
        'Position', [180, 120, 920, 620], ...
        'Color', bgColor);

    rootGrid = uigridlayout(fig, [4, 1]);
    rootGrid.RowHeight = {64, 28, 42, '1x'};
    rootGrid.Padding = [14, 14, 14, 14];
    rootGrid.RowSpacing = 10;

    pathPanel = uipanel(rootGrid, ...
        'Title', '选择连续录制 BIN 文件', ...
        'BackgroundColor', panelColor, ...
        'ForegroundColor', textColor, ...
        'FontWeight', 'bold');
    pathGrid = uigridlayout(pathPanel, [1, 2]);
    pathGrid.ColumnWidth = {130, '1x'};
    pathGrid.Padding = [8, 4, 8, 4];
    pathGrid.ColumnSpacing = 8;

    selectButton = uibutton(pathGrid, 'push', ...
        'Text', '选择 BIN 文件...', ...
        'ButtonPushedFcn', @selectAndScan, ...
        'BackgroundColor', [0.18, 0.42, 0.76], ...
        'FontColor', [1, 1, 1], ...
        'FontWeight', 'bold');
    pathField = uieditfield(pathGrid, 'text', ...
        'Value', '尚未选择文件', ...
        'Editable', 'off', ...
        'FontColor', secondaryColor, ...
        'BackgroundColor', [0.98, 0.98, 0.98]);

    progressGauge = uigauge(rootGrid, 'linear', ...
        'Limits', [0, 100], ...
        'Value', 0, ...
        'MajorTicks', [0, 25, 50, 75, 100]);

    statusLabel = uilabel(rootGrid, ...
        'Text', '等待选择 BIN 文件', ...
        'FontColor', secondaryColor, ...
        'FontSize', 12, ...
        'FontWeight', 'bold');

    logPanel = uipanel(rootGrid, ...
        'Title', '扫描信息', ...
        'BackgroundColor', panelColor, ...
        'ForegroundColor', textColor, ...
        'FontWeight', 'bold');
    logGrid = uigridlayout(logPanel, [1, 1]);
    logGrid.Padding = [8, 8, 8, 8];
    logArea = uitextarea(logGrid, ...
        'Editable', 'off', ...
        'Value', {'请选择一个 BIN 文件。'}, ...
        'FontName', 'Monospaced', ...
        'FontSize', 11, ...
        'BackgroundColor', [0.985, 0.985, 0.985], ...
        'FontColor', textColor);

    function selectAndScan(~, ~)
        [fileName, fileDir] = uigetfile( ...
            {'*.bin', 'Binary capture (*.bin)'; '*.*', 'All files'}, ...
            '选择需要检查的连续 BIN 文件', pwd);
        if isequal(fileName, 0)
            return;
        end

        binPath = fullfile(fileDir, fileName);
        [~, stem] = fileparts(fileName);
        outputPath = fullfile(fileDir, [stem, '_record_info.mat']);

        if isfile(outputPath)
            answer = uiconfirm(fig, ...
                sprintf('报告已存在，是否覆盖？\n%s', outputPath), ...
                '确认覆盖', ...
                'Options', {'覆盖', '取消'}, ...
                'DefaultOption', 2, ...
                'CancelOption', 2);
            if ~strcmp(answer, '覆盖')
                return;
            end
        end

        pathField.Value = binPath;
        pathField.FontColor = textColor;
        logArea.Value = {''};
        progressGauge.Value = 0;
        selectButton.Enable = 'off';
        statusLabel.Text = '正在扫描...';
        statusLabel.FontColor = [0.15, 0.35, 0.70];
        drawnow;

        try
            record_info = scan_bin_record_info(binPath, ...
                'ProgressFcn', @updateProgress, ...
                'LogFcn', @emitLine);

            printReport(record_info);
            atomicSave(outputPath, record_info);
            emitLine(sprintf('报告已保存: %s', outputPath));

            statusLabel.Text = sprintf('扫描完成：%s', record_info.summary.status);
            switch record_info.summary.status
                case 'PASS'
                    statusLabel.FontColor = [0.08, 0.52, 0.22];
                case 'WARN'
                    statusLabel.FontColor = [0.80, 0.48, 0.05];
                otherwise
                    statusLabel.FontColor = [0.78, 0.12, 0.12];
            end
            progressGauge.Value = 100;
        catch ME
            statusLabel.Text = '扫描失败';
            statusLabel.FontColor = [0.78, 0.12, 0.12];
            emitLine(sprintf('扫描失败: %s', ME.message));
            uialert(fig, sprintf('BIN 扫描失败：\n%s', ME.message), '扫描失败');
        end

        if isvalid(selectButton)
            selectButton.Enable = 'on';
        end
    end

    function updateProgress(fraction, message)
        if ~isvalid(fig)
            return;
        end
        progressGauge.Value = min(max(fraction * 100, 0), 100);
        statusLabel.Text = sprintf('%s  %.1f%%', message, fraction * 100);
        drawnow limitrate;
    end

    function emitLine(message)
        message = char(message);
        fprintf('%s\n', message);
        if ~isvalid(fig)
            return;
        end
        values = logArea.Value;
        if ischar(values)
            values = {values};
        end
        values{end + 1, 1} = message;
        logArea.Value = values;
        drawnow limitrate;
    end

    function printReport(info)
        emitLine('');
        emitLine('================ BIN 扫描报告 ================');
        emitLine(sprintf('文件: %s', info.file.full_path));
        emitLine(sprintf('大小: %s bytes (%.3f MiB)', ...
            formatUint(info.file.size_bytes), double(info.file.size_bytes) / 1024 / 1024));
        emitLine(sprintf('耗时: %.3f s', info.file.scan_duration_seconds));
        emitLine(sprintf('结论: %s', info.summary.status));
        emitLine(sprintf('候选帧 / 成帧 / 完全有效: %s / %s / %s', ...
            formatUint(info.summary.frame_candidates), ...
            formatUint(info.summary.framed_frame_count), ...
            formatUint(info.summary.valid_frame_count)));
        emitLine(sprintf('坏帧: %s；连续有效段: %s', ...
            formatUint(info.summary.bad_frame_count), ...
            formatUint(info.summary.continuous_segment_count)));
        emitLine(sprintf('不连续点: %s；推断缺失帧周期: %s；无法推断断点: %s', ...
            formatUint(info.summary.gap_count), ...
            formatUint(info.summary.inferred_missing_frame_count), ...
            formatUint(info.summary.unresolved_gap_count)));
        emitLine(sprintf('推断缺失总时长: %.6f秒（%s）', ...
            info.summary.inferred_missing_duration_seconds, ...
            formatDuration(info.summary.inferred_missing_duration_seconds)));
        emitLine(sprintf('内部结构问题: %s；边界残片: %s；语义疑点: %s', ...
            formatUint(info.summary.structural_issue_count), ...
            formatUint(info.summary.boundary_issue_count), ...
            formatUint(info.summary.semantic_issue_count)));
        emitLine(sprintf('BEAM错误 / 数据头错误 / 保留区错误 / 帧尾错误: %s / %s / %s / %s', ...
            formatUint(info.structural.beam_magic_error_count), ...
            formatUint(info.structural.data_header_error_count), ...
            formatUint(info.structural.beam_reserved_error_count), ...
            formatUint(info.structural.tail_error_count)));
        emitLine('CRC/状态区域: 按实际录制协议保留，本工具不校验。');
        emitLine(sprintf('跳过字节: %s；残缺尾帧字节: %s；重同步: %s', ...
            formatUint(info.structural.skipped_bytes), ...
            formatUint(info.structural.truncated_tail_bytes), ...
            formatUint(info.structural.resync_count)));
        emitLine(sprintf('波位元数据字节序: %s；出现波位数: %d', ...
            info.structural.metadata_byte_order, height(info.beam_summary)));
        emitLine(sprintf('sweep/pulse/beam语义异常: %s / %s / %s；时间戳回退: %s', ...
            formatUint(info.semantic.sweep_count.jump_forward_count + info.semantic.sweep_count.backward_nonzero_count), ...
            formatUint(info.semantic.pulse_in_beam.jump_forward_count + info.semantic.pulse_in_beam.backward_nonzero_count), ...
            formatUint(info.semantic.current_beam_idx.jump_forward_count + info.semantic.current_beam_idx.backward_nonzero_count), ...
            formatUint(info.semantic.timestamp_backward_count)));

        if ~isempty(info.gaps)
            emitLine('不连续处时间推断：');
            for row = 1:height(info.gaps)
                emitLine(sprintf(['  断点%d时间戳：前帧=%s（0x%016X），', ...
                    '后帧=%s（0x%016X），差值=%s tick。'], ...
                    info.gaps.gap_id(row), ...
                    formatUint(info.gaps.previous_timestamp(row)), ...
                    info.gaps.previous_timestamp(row), ...
                    formatUint(info.gaps.next_timestamp(row)), ...
                    info.gaps.next_timestamp(row), ...
                    formatUint(info.gaps.timestamp_delta_ticks(row))));
                if info.gaps.inference_reliable(row)
                    emitLine(sprintf(['  断点%d（段%d→%d，帧%s→%s）：缺失%s帧周期，', ...
                        '缺失时长%.6f秒（%s），物理异常区%s字节。'], ...
                        info.gaps.gap_id(row), info.gaps.previous_segment_id(row), ...
                        info.gaps.next_segment_id(row), ...
                        formatUint(info.gaps.previous_frame_index(row)), ...
                        formatUint(info.gaps.next_frame_index(row)), ...
                        formatUint(info.gaps.inferred_missing_frame_count(row)), ...
                        info.gaps.inferred_missing_duration_seconds(row), ...
                        formatDuration(info.gaps.inferred_missing_duration_seconds(row)), ...
                        formatUint(info.gaps.physical_gap_bytes(row))));
                else
                    emitLine(sprintf('  断点%d（段%d→%d）：无法可靠推断；%s', ...
                        info.gaps.gap_id(row), info.gaps.previous_segment_id(row), ...
                        info.gaps.next_segment_id(row), info.gaps.note{row}));
                end
            end
        end

        issueCount = height(info.issues);
        if issueCount > 0
            emitLine(sprintf('异常明细（显示前%d/%d条，MAT中保存全部）：', min(issueCount, 100), issueCount));
            for row = 1:min(issueCount, 100)
                emitLine(sprintf('  [%s][%s] offset=%s frame=%s %s', ...
                    info.issues.severity{row}, info.issues.type{row}, ...
                    formatUint(info.issues.byte_offset(row)), ...
                    formatUint(info.issues.frame_index(row)), ...
                    info.issues.detail{row}));
            end
        else
            emitLine('异常明细: 无');
        end
        emitLine('==============================================');
    end
end

function atomicSave(outputPath, record_info)
    outputDir = fileparts(outputPath);
    temporaryPath = [tempname(outputDir), '.mat'];
    cleanup = onCleanup(@() deleteIfExists(temporaryPath));
    save(temporaryPath, 'record_info', '-v7.3');
    [ok, message] = movefile(temporaryPath, outputPath, 'f');
    if ~ok
        error('CYHD:SaveFailed', '无法保存报告: %s', message);
    end
end

function deleteIfExists(path)
    if isfile(path)
        delete(path);
    end
end

function text = formatUint(value)
    text = sprintf('%u', uint64(value));
end

function text = formatDuration(seconds)
    if ~isfinite(seconds)
        text = '不可用';
        return;
    end
    hours = floor(seconds / 3600);
    minutes = floor(mod(seconds, 3600) / 60);
    remainingSeconds = mod(seconds, 60);
    text = sprintf('%02d:%02d:%09.6f', hours, minutes, remainingSeconds);
end
