// Code generated by stream_generate.py. DO NOT EDIT.
#pragma once

#include <common/i_data_stream.h>

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>
#include <variant>

namespace cycore {
namespace du {
namespace common {

struct Heartbeat {
    std::string status;
};

struct IQWaveform {
    uint32_t channels;
    uint32_t points;
    std::vector<int16_t> data;
};

struct FFTSpectrum {
    uint32_t channel;
    std::vector<float> data;
};

struct STFTWaterfall {
    uint32_t channel;
    uint32_t points;
    uint32_t freq_bins;
    uint32_t time_bins;
    std::vector<float> data;
};

struct RangeDoppler {
    uint32_t range_bins;
    uint32_t doppler_bins;
    std::vector<float> data;
};

struct PulseCompresssion {
    uint32_t channels;
    uint32_t points;
    std::vector<int16_t> data;
};

using StreamPayload = std::variant<
    std::monostate,
    Heartbeat,
    IQWaveform,
    FFTSpectrum,
    STFTWaterfall,
    RangeDoppler,
    PulseCompresssion
>;

struct StreamFrameEvent {
    std::string node_id;
    std::string topic;
    uint64_t seq;
    uint64_t timestamp_unix_nano;
    cy::common::DataType data_type = cy::common::DataType::RawBytes;
    std::vector<std::byte> data;
};

} // namespace common
} // namespace du
} // namespace cycore
