# syntax=docker/dockerfile:1
FROM --platform=linux/arm64 ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    libucx0 \
    ucx-utils \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*
